



FROM microsoft/dotnet:2.1-sdk-nanoserver-1803 AS build
WORKDIR /src
COPY ["CISampleApplication/CISampleApplication.csproj", "CISampleApplication/"]
RUN dotnet restore "CISampleApplication/CISampleApplication.csproj"
COPY . .
WORKDIR "/src/CISampleApplication"
RUN dotnet build "CISampleApplication.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "CISampleApplication.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "CISampleApplication.dll"]
